In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.20.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)

In [9]:
from sklearn import linear_model

In [12]:
file=pd.read_csv(r"C:\Users\Uer\Downloads\canada_per_capita_income.csv")

In [13]:
file

    year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

In [14]:
model_1=linear_model.LinearRegression()

In [15]:
new_File=file.drop("per capita income (US$)",axis="columns")

In [16]:
new_File

    year
0   1970
1   1971
2   1972
3   1973
4   1974
5   1975
6   1976
7   1977
8   1978
9   1979
10  1980
11  1981
12  1982
13  1983
14  1984
15  1985
16  1986
17  1987
18  1988
19  1989
20  1990
21  1991
22  1992
23  1993
24  1994
25  1995
26  1996
27  1997
28  1998
29  1999
30  2000
31  2001
32  2002
33  2003
34  2004
35  2005
36  2006
37  2007
38  2008
39  2009
40  2010
41  2011
42  2012
43  2013
44  2014
45  2015
46  2016

In [19]:
model_1.fit(new_File,file["per capita income (US$)"])

LinearRegression()

In [20]:
model_1.predict([[2020]])

C:\Users\Uer\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([41288.69409442])

In [21]:
model_1.intercept_

np.float64(-1632210.7578554575)

In [23]:
model_1.coef_

array([828.46507522])

In [25]:
#Y=mX+b(EQUATION),Lets X is Equal to 2020
828.46507522 * 2020 + (-1632210.7578554575)

41288.694088942604

In [27]:
file2=pd.read_csv(r"C:\Users\Uer\Downloads\records (1).csv")

In [28]:
file2

    year  per capita income (US$)
0   1970                      NaN
1   1971                      NaN
2   1972                      NaN
3   1973                      NaN
4   1974                      NaN
5   1975                      NaN
6   1976                      NaN
7   1977                      NaN
8   1978                      NaN
9   1979                      NaN
10  1980                      NaN
11  1981                      NaN
12  1982                      NaN
13  1983                      NaN
14  1984                      NaN
15  1985                      NaN
16  1986                      NaN
17  1987                      NaN
18  1988                      NaN
19  1989                      NaN
20  1990                      NaN
21  1991                      NaN
22  1992                      NaN
23  1993                      NaN
24  1994                      NaN
25  1995                      NaN
26  1996                      NaN
27  1997                      NaN
28  1998                      NaN
29  1999                      NaN
30  2000                      NaN
31  2001                      NaN
32  2002                      NaN
33  2003                      NaN
34  2004                      NaN
35  2005                      NaN
36  2006                      NaN
37  2007                      NaN
38  2008                      NaN
39  2009                      NaN
40  2010                      NaN
41  2011                      NaN
42  2012                      NaN
43  2013                      NaN
44  2014                      NaN
45  2015                      NaN
46  2016                      NaN

In [29]:
file_2=file2.drop("per capita income (US$)",axis="columns")

In [30]:
file_2

    year
0   1970
1   1971
2   1972
3   1973
4   1974
5   1975
6   1976
7   1977
8   1978
9   1979
10  1980
11  1981
12  1982
13  1983
14  1984
15  1985
16  1986
17  1987
18  1988
19  1989
20  1990
21  1991
22  1992
23  1993
24  1994
25  1995
26  1996
27  1997
28  1998
29  1999
30  2000
31  2001
32  2002
33  2003
34  2004
35  2005
36  2006
37  2007
38  2008
39  2009
40  2010
41  2011
42  2012
43  2013
44  2014
45  2015
46  2016

In [32]:
p=model_1.predict(file_2)
p

array([ -134.55966672,   693.9054085 ,  1522.37048373,  2350.83555895,
        3179.30063417,  4007.7657094 ,  4836.23078462,  5664.69585984,
        6493.16093506,  7321.62601029,  8150.09108551,  8978.55616073,
        9807.02123595, 10635.48631118, 11463.9513864 , 12292.41646162,
       13120.88153685, 13949.34661207, 14777.81168729, 15606.27676251,
       16434.74183774, 17263.20691296, 18091.67198818, 18920.1370634 ,
       19748.60213863, 20577.06721385, 21405.53228907, 22233.9973643 ,
       23062.46243952, 23890.92751474, 24719.39258996, 25547.85766519,
       26376.32274041, 27204.78781563, 28033.25289085, 28861.71796608,
       29690.1830413 , 30518.64811652, 31347.11319175, 32175.57826697,
       33004.04334219, 33832.50841741, 34660.97349264, 35489.43856786,
       36317.90364308, 37146.3687183 , 37974.83379353])

In [34]:
file_2["per capita income (US$)"]=p

In [38]:
file_2.to_csv("Records.csv")